package com.askit.app.explore

import com.askit.designsystem.tasks.TaskResultStatus

fun sampleExplorePeople(): List<ExplorePersonResult> = listOf(
    ExplorePersonResult(
        id = "pro-1",
        name = "Priya Sharma",
        avatarUrl = "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300",
        primaryService = "Electrician",
        additionalServices = listOf("Inverter repair", "Wiring", "Ceiling Fan"),
        rating = 4.9,
        reviewCount = 48,
        locationLabel = "1.2 km away",
        priceLabel = "₹350/hr",
        statusLabel = "Available now",
        matchReasons = setOf(PersonMatchReason.Identity, PersonMatchReason.Service),
    ),
    ExplorePersonResult(
        id = "pro-2",
        name = "Suresh Kumar",
        avatarUrl = "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300",
        primaryService = "Plumber",
        additionalServices = listOf("Pipe leak fix", "Tap replacement", "Water tank clean"),
        rating = 4.8,
        reviewCount = 62,
        locationLabel = "2.5 km away",
        priceLabel = "₹400/hr",
        statusLabel = "Available today",
        matchReasons = setOf(PersonMatchReason.Identity, PersonMatchReason.Service),
    ),
    ExplorePersonResult(
        id = "pro-3",
        name = "Ananya Roy",
        avatarUrl = "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=300",
        primaryService = "Cleaning",
        additionalServices = listOf("Deep house clean", "Kitchen clean", "Sofa wash"),
        rating = 4.9,
        reviewCount = 89,
        locationLabel = "3.1 km away",
        priceLabel = "₹799/visit",
        statusLabel = "Available tomorrow",
        matchReasons = setOf(PersonMatchReason.Identity, PersonMatchReason.Service),
    ),
    ExplorePersonResult(
        id = "pro-4",
        name = "Karthik Raja",
        avatarUrl = "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300",
        primaryService = "AC Repair & Service",
        additionalServices = listOf("Gas refill", "Filter service", "Installation"),
        rating = 4.7,
        reviewCount = 35,
        locationLabel = "4.0 km away",
        priceLabel = "₹599/service",
        statusLabel = "Available today",
        matchReasons = setOf(PersonMatchReason.Identity, PersonMatchReason.Service),
    ),
    ExplorePersonResult(
        id = "pro-5",
        name = "Divya Nair",
        avatarUrl = "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300",
        primaryService = "Home Tutor",
        additionalServices = listOf("Math & Science (Grades 6-10)", "CBSE & ICSE", "Exam prep"),
        rating = 5.0,
        reviewCount = 24,
        locationLabel = "1.8 km away",
        priceLabel = "₹500/hr",
        statusLabel = "Evenings",
        matchReasons = setOf(PersonMatchReason.Identity, PersonMatchReason.Service),
    ),
    ExplorePersonResult(
        id = "pro-6",
        name = "Ramesh Babu",
        avatarUrl = "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=300",
        primaryService = "Appliance Repair",
        additionalServices = listOf("Washing machine", "Refrigerator", "Microwave"),
        rating = 4.8,
        reviewCount = 53,
        locationLabel = "3.5 km away",
        priceLabel = "₹450/visit",
        statusLabel = "Available today",
        matchReasons = setOf(PersonMatchReason.Identity, PersonMatchReason.Service),
    ),
)

fun sampleExploreTasks(): List<ExploreTaskResult> = listOf(
    ExploreTaskResult(
        id = "task-1",
        title = "Fix kitchen sink drainage leak & replace mixer tap",
        category = "Plumbing",
        summary = "Water leaking from P-trap beneath the kitchen sink. Need replacement pipe and fitting.",
        budgetLabel = "₹800",
        locationLabel = "Gandhipuram (1.5 km)",
        timingLabel = "Today by 6 PM",
        posterName = "Meera R.",
        postedLabel = "20m ago",
        status = TaskResultStatus.Open,
        distanceLabel = "1.5 km",
    ),
    ExploreTaskResult(
        id = "task-2",
        title = "Install 2 ceiling fans & fix bedroom switchboard",
        category = "Electrical",
        summary = "Two new Havells fans to be mounted. Wiring is already pulled.",
        budgetLabel = "₹600",
        locationLabel = "RS Puram (2.8 km)",
        timingLabel = "Tomorrow morning",
        posterName = "Karthik V.",
        postedLabel = "1h ago",
        status = TaskResultStatus.Open,
        distanceLabel = "2.8 km",
    ),
    ExploreTaskResult(
        id = "task-3",
        title = "Full 2BHK deep cleaning before moving in",
        category = "Cleaning",
        summary = "Empty flat needs floor scrubbing, bathroom deep sanitization, and balcony wash.",
        budgetLabel = "₹2,500",
        locationLabel = "Saibaba Colony (3.4 km)",
        timingLabel = "This Weekend",
        posterName = "Deepak S.",
        postedLabel = "3h ago",
        status = TaskResultStatus.Open,
        distanceLabel = "3.4 km",
    ),
    ExploreTaskResult(
        id = "task-4",
        title = "Split AC water dripping inside room",
        category = "AC Repair",
        summary = "1.5 Ton Voltas indoor unit leaks water when running continuously for over an hour.",
        budgetLabel = "₹900",
        locationLabel = "Peelamedu (4.2 km)",
        timingLabel = "Flexible this week",
        posterName = "Sneha M.",
        postedLabel = "5h ago",
        status = TaskResultStatus.Open,
        distanceLabel = "4.2 km",
    ),
)
